apiVersion: v1
kind: Service
metadata:
  name: twin-app-svc
  namespace: twin-${ENV}
  labels:
    app: twin-app
spec:
  selector:
    app: twin-app
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP